name: Scan Offline

on:
  push:
    branches:
      - trivy-offline  # Trigger for the feature branch

jobs:
  Scan:
    runs-on: ubuntu-latest

    steps:

      # Step to check GitHub Actions Runner Version
      - name: Check GitHub Actions Runner Version
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "GitHub Actions version: $GITHUB_ACTIONS_VERSION"
          echo "GitHub Ref: $GITHUB_REF"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "Repository: $GITHUB_REPOSITORY"
      
      # Step to dump environment variables
      - name: Dump environment variables
        run: env

      # Check the GITHUB_TOKEN permissions using GitHub API
      - name: Check GITHUB_TOKEN Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}


      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # Step 3: Restore .NET dependencies and update lock file
      - name: Restore and update lock file
        run: dotnet restore ./src/MySampleDotNetApp/MySampleDotNetApp.csproj --use-lock-file --force-evaluate

      # Step 4: Download Trivy DB if available from cache
      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: /tmp/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}  # Use a unique key
          restore-keys: |
            trivy-db-${{ runner.os }}-
            trivy-db-

      # Step 5: Run Trivy scan in offline mode
      - name: Run Trivy scan (Offline)
        uses: docker://aquasec/aqua-scanner
        with:
          args: |
            trivy fs --offline-scan --skip-db-update --skip-java-db-update --skip-check-update --sast --reachability --scanners misconfig,vuln,secret /github/workspace
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AQUA_URL: ${{ vars.AQUA_URL }}
          CSPM_URL: ${{ vars.CSPM_URL }}
          TRIVY_RUN_AS_PLUGIN: "aqua"
          TRIVY_CACHE_DIR: /tmp/.cache/trivy  # Specify the cache directory

      # Step 6: Cleanup Cache Lock File
      - name: Cleanup Trivy Cache Lock File
        run: |
          if [ -f /tmp/.cache/trivy/lock ]; then
            rm /tmp/.cache/trivy/lock
          fi
