name: Download and Populate Trivy Databases

on:
  push:
    branches:
      - trivy-offline  # Trigger for the feature branch

jobs:
  DownloadAndCacheDB:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Download Trivy databases
      - name: Download Trivy Databases
        uses: docker://aquasec/aqua-scanner
        with:
          args: |
            trivy image \
              --cache-dir /tmp/.cache/trivy \
              --download-db-only \
              --no-progress \
              --db-repository ghcr.io/aquasecurity/trivy-db:2 \
              --java-db-repository ghcr.io/aquasecurity/trivy-java-db:1

      # Step 3: Cache Trivy DB
      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: /tmp/.cache/trivy  # Use the correct cache path for Trivy
          key: trivy-db-${{ runner.os }}-${{ github.sha }}  # Use a unique key
          restore-keys: |
            trivy-db-${{ runner.os }}-
            trivy-db-
