name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your Java version

      - name: Download Trivy Database
        run: |
          trivy image --cache-dir /tmp/.cache/trivy --download-db-only --no-progress --db-repository ghcr.io/aquasecurity/trivy-db:2 --java-db-repository ghcr.io/aquasecurity/trivy-java-db:1 --checks-bundle-repository ghcr.io/aquasecurity/trivy-checks:0

      - name: Check Trivy Cache
        run: |
          echo "Contents of $HOME/.cache/trivy:"
          ls -la $HOME/.cache/trivy
          if [ -d $HOME/.cache/trivy/db ]; then
            echo "Databases downloaded successfully."
            ls -la $HOME/.cache/trivy/db
          else
            echo "Databases not found!"
            exit 1
          fi

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/trivy  # Cache the entire cache directory
          key: trivy-db-${{ runner.os }}-${{ github.sha }}  # Unique key for caching
          restore-keys: |
            trivy-db-${{ runner.os }}-
            trivy-db-
          save-always: true  # Optional: Save cache even if it doesn't match the key

      - name: Run Trivy Scan
        run: |
          trivy image --cache-dir /tmp/.cache/trivy my-image:latest  # Replace with your image
