name: Download and Populate Trivy Databases

on:
  push:
    branches:
      - trivy-offline

jobs:
  DownloadAndCacheDB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Cache Directory
        run: mkdir -p $HOME/.cache/trivy/db  # Ensure the db directory exists

      - name: Download Trivy Databases
        id: download_trivy
        run: |
          docker run --user $(id -u):$(id -g) -v $HOME/.cache/trivy:/tmp/.cache/trivy aquasec/aqua-scanner trivy image \
            --cache-dir /tmp/.cache/trivy \
            --download-db-only \
            --no-progress \
            --db-repository ghcr.io/aquasecurity/trivy-db:2 \
            --java-db-repository ghcr.io/aquasecurity/trivy-java-db:1 \
            --checks-bundle-repository ghcr.io/aquasecurity/trivy-checks:0

      - name: Verify Cache Directory After Download
        run: |
          echo "Contents of $HOME/.cache/trivy:"
          ls -la $HOME/.cache/trivy
          if [ -d $HOME/.cache/trivy/db ]; then
            echo "Databases downloaded successfully."
            ls -la $HOME/.cache/trivy/db
          else
            echo "Databases not found!"
            exit 1
          fi

      - name: Check for Cache Path Before Caching
        run: |
          echo "Checking contents of the cache path for caching..."
          if [ -d $HOME/.cache/trivy/db ]; then
            echo "Cache path exists. Contents:"
            ls -la $HOME/.cache/trivy/db
          else
            echo "Cache path does not exist!"
            exit 1
          fi

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: $HOME/.cache/trivy/db/*  # Ensure we cache the contents of the db directory
          key: trivy-db-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            trivy-db-${{ runner.os }}-
            trivy-db-
