name: Download and Populate Trivy Databases

on:
  push:
    branches:
      - trivy-offline

jobs:
  DownloadAndCacheDB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Cache Directory
        run: mkdir -p /tmp/.cache/trivy

      - name: Download Trivy Databases
        id: download_trivy
        run: |
          docker run -v /tmp/.cache/trivy:/tmp/.cache/trivy aquasec/aqua-scanner trivy image \
            --cache-dir /tmp/.cache/trivy \
            --download-db-only \
            --no-progress \
            --db-repository ghcr.io/aquasecurity/trivy-db:2 \
            --java-db-repository ghcr.io/aquasecurity/trivy-java-db:1 \
            --checks-bundle-repository ghcr.io/aquasecurity/trivy-checks:0

      - name: Verify Cache Directory
        run: |
          echo "Contents of /tmp/.cache/trivy:"
          ls -la /tmp/.cache/trivy
          if [ -d /tmp/.cache/trivy/db ]; then
            echo "Databases downloaded successfully."
            ls -la /tmp/.cache/trivy/db
          else
            echo "Databases not found!"
            exit 1
          fi

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: /tmp/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            trivy-db-${{ runner.os }}-
            trivy-db-
